modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL v3.0"
[[mods]]
modId = "${mod_id}"
version = "${addon_version}"
displayName = "${mod_name}"
displayURL = "https://discord.gg/4GcjnMnXP4"
updateJSONURL="https://raw.githubusercontent.com/Weever1337/MadeInHeavenRotpAddon/main/update.json"
authors = "${mod_authors}"
logoFile="logo.png"
credits="StandoByte, Makuta Zeml"
description='''
An Addon that adds Made in Heaven to Ripples of the Past.

Localization (Discords):
- English (en_us): weeverlegend
- Ukrainian (uk_ua): weeverlegend
- Russian (ru_ru): weeverlegend
- Chinese (zh_cn): johnny_joestar2804'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="jojo"
mandatory=true
versionRange="[0.2.2,0.3)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="hourglass"
mandatory=true
versionRange="[1.2,1.3)"
ordering="AFTER"
side="BOTH"
